package com.myteam.tts_connected_claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class assessmentCustomerDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("customerFirstName")
	private java.lang.String customerFirstName;
	@org.kie.api.definition.type.Label("title")
	private java.lang.String title;
	@org.kie.api.definition.type.Label("customerInitials")
	private java.lang.String customerInitials;
	@org.kie.api.definition.type.Label("customerSurName")
	private java.lang.String customerSurName;
	@org.kie.api.definition.type.Label("contactNumber")
	private java.lang.String contactNumber;
	@org.kie.api.definition.type.Label("dateOfBirth")
	private java.lang.String dateOfBirth;
	@org.kie.api.definition.type.Label("riskAddress")
	private com.myteam.tts_connected_claims.riskAddress riskAddress;

	@org.kie.api.definition.type.Label(value = "customerId")
	private java.lang.String customerId;

	public assessmentCustomerDetails() {
	}

	public java.lang.String getCustomerFirstName() {
		return this.customerFirstName;
	}

	public void setCustomerFirstName(java.lang.String customerFirstName) {
		this.customerFirstName = customerFirstName;
	}

	public java.lang.String getTitle() {
		return this.title;
	}

	public void setTitle(java.lang.String title) {
		this.title = title;
	}

	public java.lang.String getCustomerInitials() {
		return this.customerInitials;
	}

	public void setCustomerInitials(java.lang.String customerInitials) {
		this.customerInitials = customerInitials;
	}

	public java.lang.String getCustomerSurName() {
		return this.customerSurName;
	}

	public void setCustomerSurName(java.lang.String customerSurName) {
		this.customerSurName = customerSurName;
	}

	public java.lang.String getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(java.lang.String contactNumber) {
		this.contactNumber = contactNumber;
	}

	public java.lang.String getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(java.lang.String dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public com.myteam.tts_connected_claims.riskAddress getRiskAddress() {
		return this.riskAddress;
	}

	public void setRiskAddress(
			com.myteam.tts_connected_claims.riskAddress riskAddress) {
		this.riskAddress = riskAddress;
	}

	public java.lang.String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(java.lang.String customerId) {
		this.customerId = customerId;
	}

	public assessmentCustomerDetails(java.lang.String customerFirstName,
			java.lang.String title, java.lang.String customerInitials,
			java.lang.String customerSurName, java.lang.String contactNumber,
			java.lang.String dateOfBirth,
			com.myteam.tts_connected_claims.riskAddress riskAddress,
			java.lang.String customerId) {
		this.customerFirstName = customerFirstName;
		this.title = title;
		this.customerInitials = customerInitials;
		this.customerSurName = customerSurName;
		this.contactNumber = contactNumber;
		this.dateOfBirth = dateOfBirth;
		this.riskAddress = riskAddress;
		this.customerId = customerId;
	}

}