package com.myteam.tts_connected_claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class assessmentPolicyDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("brokerCode")
	private java.lang.String brokerCode;
	@org.kie.api.definition.type.Label("brokerDescription")
	private java.lang.String brokerDescription;
	@org.kie.api.definition.type.Label("contactNumber")
	private java.lang.String contactNumber;
	@org.kie.api.definition.type.Label("email")
	private java.lang.String email;
	@org.kie.api.definition.type.Label("policyConcellationDate")
	private java.lang.String policyConcellationDate;
	@org.kie.api.definition.type.Label("policyCommencementTime")
	private java.lang.String policyCommencementTime;
	@org.kie.api.definition.type.Label("policyCommencementDate")
	private java.lang.String policyCommencementDate;
	@org.kie.api.definition.type.Label("policyHolderFirstName")
	private java.lang.String policyHolderFirstName;
	@org.kie.api.definition.type.Label("policyHolderId")
	private java.lang.String policyHolderId;
	@org.kie.api.definition.type.Label("policHolderSurName")
	private java.lang.String policyHolderSurName;
	@org.kie.api.definition.type.Label("policyInactiveReason")
	private java.lang.String policyInactiveReason;
	@org.kie.api.definition.type.Label("policyHolderInitials")
	private java.lang.String policyHolderInitials;
	@org.kie.api.definition.type.Label("policyNumber")
	private java.lang.String policyNumber;
	@org.kie.api.definition.type.Label("policyStatus")
	private java.lang.String policyStatus;
	@org.kie.api.definition.type.Label("title")
	private java.lang.String title;

	@org.kie.api.definition.type.Label("dateOfBirth")
	private java.lang.String dateOfBirth;

	@org.kie.api.definition.type.Label(value = "policyCancellationTime")
	private java.lang.String policyCancellationTime;

	public assessmentPolicyDetails() {
	}

	public java.lang.String getBrokerCode() {
		return this.brokerCode;
	}

	public void setBrokerCode(java.lang.String brokerCode) {
		this.brokerCode = brokerCode;
	}

	public java.lang.String getBrokerDescription() {
		return this.brokerDescription;
	}

	public void setBrokerDescription(java.lang.String brokerDescription) {
		this.brokerDescription = brokerDescription;
	}

	public java.lang.String getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(java.lang.String contactNumber) {
		this.contactNumber = contactNumber;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getPolicyConcellationDate() {
		return this.policyConcellationDate;
	}

	public void setPolicyConcellationDate(
			java.lang.String policyConcellationDate) {
		this.policyConcellationDate = policyConcellationDate;
	}

	public java.lang.String getPolicyCommencementTime() {
		return this.policyCommencementTime;
	}

	public void setPolicyCommencementTime(
			java.lang.String policyCommencementTime) {
		this.policyCommencementTime = policyCommencementTime;
	}

	public java.lang.String getPolicyCommencementDate() {
		return this.policyCommencementDate;
	}

	public void setPolicyCommencementDate(
			java.lang.String policyCommencementDate) {
		this.policyCommencementDate = policyCommencementDate;
	}

	public java.lang.String getPolicyHolderFirstName() {
		return this.policyHolderFirstName;
	}

	public void setPolicyHolderFirstName(java.lang.String policyHolderFirstName) {
		this.policyHolderFirstName = policyHolderFirstName;
	}

	public java.lang.String getPolicyHolderId() {
		return this.policyHolderId;
	}

	public void setPolicyHolderId(java.lang.String policyHolderId) {
		this.policyHolderId = policyHolderId;
	}

	public java.lang.String getPolicyHolderSurName() {
		return this.policyHolderSurName;
	}

	public void setPolicyHolderSurName(java.lang.String policyHolderSurName) {
		this.policyHolderSurName = policyHolderSurName;
	}

	public java.lang.String getPolicyInactiveReason() {
		return this.policyInactiveReason;
	}

	public void setPolicyInactiveReason(java.lang.String policyInactiveReason) {
		this.policyInactiveReason = policyInactiveReason;
	}

	public java.lang.String getPolicyHolderInitials() {
		return this.policyHolderInitials;
	}

	public void setPolicyHolderInitials(java.lang.String policyHolderInitials) {
		this.policyHolderInitials = policyHolderInitials;
	}

	public java.lang.String getPolicyNumber() {
		return this.policyNumber;
	}

	public void setPolicyNumber(java.lang.String policyNumber) {
		this.policyNumber = policyNumber;
	}

	public java.lang.String getPolicyStatus() {
		return this.policyStatus;
	}

	public void setPolicyStatus(java.lang.String policyStatus) {
		this.policyStatus = policyStatus;
	}

	public java.lang.String getTitle() {
		return this.title;
	}

	public void setTitle(java.lang.String title) {
		this.title = title;
	}

	public java.lang.String getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(java.lang.String dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public java.lang.String getPolicyCancellationTime() {
		return this.policyCancellationTime;
	}

	public void setPolicyCancellationTime(
			java.lang.String policyCancellationTime) {
		this.policyCancellationTime = policyCancellationTime;
	}

	public assessmentPolicyDetails(java.lang.String brokerCode,
			java.lang.String brokerDescription, java.lang.String contactNumber,
			java.lang.String email, java.lang.String policyConcellationDate,
			java.lang.String policyCommencementTime,
			java.lang.String policyCommencementDate,
			java.lang.String policyHolderFirstName,
			java.lang.String policyHolderId,
			java.lang.String policyHolderSurName,
			java.lang.String policyInactiveReason,
			java.lang.String policyHolderInitials,
			java.lang.String policyNumber, java.lang.String policyStatus,
			java.lang.String title, java.lang.String dateOfBirth,
			java.lang.String policyCancellationTime) {
		this.brokerCode = brokerCode;
		this.brokerDescription = brokerDescription;
		this.contactNumber = contactNumber;
		this.email = email;
		this.policyConcellationDate = policyConcellationDate;
		this.policyCommencementTime = policyCommencementTime;
		this.policyCommencementDate = policyCommencementDate;
		this.policyHolderFirstName = policyHolderFirstName;
		this.policyHolderId = policyHolderId;
		this.policyHolderSurName = policyHolderSurName;
		this.policyInactiveReason = policyInactiveReason;
		this.policyHolderInitials = policyHolderInitials;
		this.policyNumber = policyNumber;
		this.policyStatus = policyStatus;
		this.title = title;
		this.dateOfBirth = dateOfBirth;
		this.policyCancellationTime = policyCancellationTime;
	}

}