package com.myteam.tts_connected_claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class escalatedServices implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "escalationReason")
	private java.lang.String escalatedServices;
	@org.kie.api.definition.type.Label(value = "serviceSubType")
	private java.lang.String serviceSubType;
	@org.kie.api.definition.type.Label(value = "serviceType")
	private java.lang.String serviceType;

	public escalatedServices() {
	}

	public java.lang.String getEscalatedServices() {
		return this.escalatedServices;
	}

	public void setEscalatedServices(java.lang.String escalatedServices) {
		this.escalatedServices = escalatedServices;
	}

	public java.lang.String getServiceSubType() {
		return this.serviceSubType;
	}

	public void setServiceSubType(java.lang.String serviceSubType) {
		this.serviceSubType = serviceSubType;
	}

	public java.lang.String getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(java.lang.String serviceType) {
		this.serviceType = serviceType;
	}

	public escalatedServices(java.lang.String escalatedServices,
			java.lang.String serviceSubType, java.lang.String serviceType) {
		this.escalatedServices = escalatedServices;
		this.serviceSubType = serviceSubType;
		this.serviceType = serviceType;
	}

}