package com.myteam.tts_connected_claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class escalationBO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("breachLimit")
	private java.lang.String breachLimit;
	@org.kie.api.definition.type.Label("caseType")
	private java.lang.String caseType;

	@org.kie.api.definition.type.Label("dispatchInitiationMethod")
	private java.lang.String dispatchInitiationMethod;

	@org.kie.api.definition.type.Label("dispatchMethod")
	private java.lang.String dispatchMethod;

	@org.kie.api.definition.type.Label("fromStatus")
	private java.lang.String fromStatus;

	@org.kie.api.definition.type.Label("incidentId")
	private java.lang.String incidentId;

	@org.kie.api.definition.type.Label("processInstanceId")
	private java.lang.String processInstanceId;

	@org.kie.api.definition.type.Label("serviceId")
	private java.lang.String serviceId;

	@org.kie.api.definition.type.Label("serviceType")
	private java.lang.String serviceType;

	@org.kie.api.definition.type.Label("slaBreached")
	private java.lang.Boolean slaBreached;

	@org.kie.api.definition.type.Label("toStatus")
	private java.lang.String toStatus;

	@org.kie.api.definition.type.Label("triggerType")
	private java.lang.String triggerType;

	@org.kie.api.definition.type.Label(value = "active")
	private java.lang.Boolean active;

	public escalationBO() {
	}

	public java.lang.String getBreachLimit() {
		return this.breachLimit;
	}

	public void setBreachLimit(java.lang.String breachLimit) {
		this.breachLimit = breachLimit;
	}

	public java.lang.String getCaseType() {
		return this.caseType;
	}

	public void setCaseType(java.lang.String caseType) {
		this.caseType = caseType;
	}

	public java.lang.String getDispatchInitiationMethod() {
		return this.dispatchInitiationMethod;
	}

	public void setDispatchInitiationMethod(
			java.lang.String dispatchInitiationMethod) {
		this.dispatchInitiationMethod = dispatchInitiationMethod;
	}

	public java.lang.String getDispatchMethod() {
		return this.dispatchMethod;
	}

	public void setDispatchMethod(java.lang.String dispatchMethod) {
		this.dispatchMethod = dispatchMethod;
	}

	public java.lang.String getFromStatus() {
		return this.fromStatus;
	}

	public void setFromStatus(java.lang.String fromStatus) {
		this.fromStatus = fromStatus;
	}

	public java.lang.String getIncidentId() {
		return this.incidentId;
	}

	public void setIncidentId(java.lang.String incidentId) {
		this.incidentId = incidentId;
	}

	public java.lang.String getProcessInstanceId() {
		return this.processInstanceId;
	}

	public void setProcessInstanceId(java.lang.String processInstanceId) {
		this.processInstanceId = processInstanceId;
	}

	public java.lang.String getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(java.lang.String serviceId) {
		this.serviceId = serviceId;
	}

	public java.lang.String getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(java.lang.String serviceType) {
		this.serviceType = serviceType;
	}

	public java.lang.Boolean getSlaBreached() {
		return this.slaBreached;
	}

	public void setSlaBreached(java.lang.Boolean slaBreached) {
		this.slaBreached = slaBreached;
	}

	public java.lang.String getToStatus() {
		return this.toStatus;
	}

	public void setToStatus(java.lang.String toStatus) {
		this.toStatus = toStatus;
	}

	public java.lang.String getTriggerType() {
		return this.triggerType;
	}

	public void setTriggerType(java.lang.String triggerType) {
		this.triggerType = triggerType;
	}

	public java.lang.Boolean getActive() {
		return this.active;
	}

	public void setActive(java.lang.Boolean active) {
		this.active = active;
	}

	public escalationBO(java.lang.String breachLimit,
			java.lang.String caseType,
			java.lang.String dispatchInitiationMethod,
			java.lang.String dispatchMethod, java.lang.String fromStatus,
			java.lang.String incidentId, java.lang.String processInstanceId,
			java.lang.String serviceId, java.lang.String serviceType,
			java.lang.Boolean slaBreached, java.lang.String toStatus,
			java.lang.String triggerType, java.lang.Boolean active) {
		this.breachLimit = breachLimit;
		this.caseType = caseType;
		this.dispatchInitiationMethod = dispatchInitiationMethod;
		this.dispatchMethod = dispatchMethod;
		this.fromStatus = fromStatus;
		this.incidentId = incidentId;
		this.processInstanceId = processInstanceId;
		this.serviceId = serviceId;
		this.serviceType = serviceType;
		this.slaBreached = slaBreached;
		this.toStatus = toStatus;
		this.triggerType = triggerType;
		this.active = active;
	}

}