package com.myteam.tts_connected_claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class previousServiceProviders implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PREVIOUSSERVICEPROVIDERS_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "PREVIOUSSERVICEPROVIDERS_ID_SEQ", name = "PREVIOUSSERVICEPROVIDERS_ID_GENERATOR")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("contactNumber")
	private java.lang.String contactNumber;

	@org.kie.api.definition.type.Label("email")
	private java.lang.String email;

	@org.kie.api.definition.type.Label("firstName")
	private java.lang.String firstName;

	@org.kie.api.definition.type.Label("surname")
	private java.lang.String surname;

	@org.kie.api.definition.type.Label(value = "status")
	private java.lang.String status;

	public previousServiceProviders() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(java.lang.String contactNumber) {
		this.contactNumber = contactNumber;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(java.lang.String firstName) {
		this.firstName = firstName;
	}

	public java.lang.String getSurname() {
		return this.surname;
	}

	public void setSurname(java.lang.String surname) {
		this.surname = surname;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public previousServiceProviders(java.lang.Long id,
			java.lang.String contactNumber, java.lang.String email,
			java.lang.String firstName, java.lang.String surname,
			java.lang.String status) {
		this.id = id;
		this.contactNumber = contactNumber;
		this.email = email;
		this.firstName = firstName;
		this.surname = surname;
		this.status = status;
	}

}