package com.myteam.tts_connected_claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class risk implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "sequenceNumber")
	private java.lang.String sequenceNumber;
	@org.kie.api.definition.type.Label(value = "riskItem")
	private java.lang.String riskItem;

	public risk() {
	}

	public java.lang.String getSequenceNumber() {
		return this.sequenceNumber;
	}

	public void setSequenceNumber(java.lang.String sequenceNumber) {
		this.sequenceNumber = sequenceNumber;
	}

	public java.lang.String getRiskItem() {
		return this.riskItem;
	}

	public void setRiskItem(java.lang.String riskItem) {
		this.riskItem = riskItem;
	}

	public risk(java.lang.String sequenceNumber, java.lang.String riskItem) {
		this.sequenceNumber = sequenceNumber;
		this.riskItem = riskItem;
	}

}