package com.myteam.tts_connected_claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class riskAddress implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("street2")
	private java.lang.String street2;

	@org.kie.api.definition.type.Label("street3")
	private java.lang.String street3;

	@org.kie.api.definition.type.Label("suburb")
	private java.lang.String suburb;

	@org.kie.api.definition.type.Label("postalCode")
	private java.lang.String postalCode;

	@org.kie.api.definition.type.Label(value = "street")
	private java.lang.String street;

	public riskAddress() {
	}

	public java.lang.String getStreet2() {
		return this.street2;
	}

	public void setStreet2(java.lang.String street2) {
		this.street2 = street2;
	}

	public java.lang.String getStreet3() {
		return this.street3;
	}

	public void setStreet3(java.lang.String street3) {
		this.street3 = street3;
	}

	public java.lang.String getSuburb() {
		return this.suburb;
	}

	public void setSuburb(java.lang.String suburb) {
		this.suburb = suburb;
	}

	public java.lang.String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(java.lang.String postalCode) {
		this.postalCode = postalCode;
	}

	public java.lang.String getStreet() {
		return this.street;
	}

	public void setStreet(java.lang.String street) {
		this.street = street;
	}

	public riskAddress(java.lang.String street2, java.lang.String street3,
			java.lang.String suburb, java.lang.String postalCode,
			java.lang.String street) {
		this.street2 = street2;
		this.street3 = street3;
		this.suburb = suburb;
		this.postalCode = postalCode;
		this.street = street;
	}

}